### ISSUE TITLE
Proof of concept d3js with metasfresh WebUI Dashboard

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui#64]
Proof of concept d3js (or similar chart tool) with metasfresh WebUI Dashboard

- shall be seemlessly embedable
- no unsmooth loading time when opening/ refreshing dashboard (lightening fast)
- transitions/ animations possible

what would a general approach look like? how would the config look like on backend/ frontend?

https://github.com/d3/d3/wiki/Gallery

**Comment by damianprzygodzki** [comment]
The most important thing is to say what type of charts would it be? Because i have to make sure if i can get something that is ready, or we need any custom drawings.

Second thing, if we are gonna have a "library" of charts (as we have with widgets), the layouting would be the same as with widgets.

And i believe that we can deliver data to that, with our protocols that we have: 1) static API calls, i.e. refreshed some time, 2) websockets to have it more relative

**Comment by teosarca** [comment]
Hi,

1. i think we shall build a list of what kind of charts do we need.
2. then we shall define an API protocol about how the indicators will be defined and provided.

About:
> And i believe that we can deliver data to that, with our protocols that we have: 1) static API calls, i.e. refreshed some time, 2) websockets to have it more relative

AFAIK, elasicsearch does not support continuous queries so i think polling (via API calls) it's the only option atm.

**Comment by metas-mk** [comment]
I was thinking about "Basic Charts" first
see https://github.com/d3/d3/wiki/Gallery#basic-charts
and from those for poc we could take for example a simple bar chart or pie chart.

**Comment by teosarca** [comment]
Backend implementation task: #184
